[project]
name = "datamodel-code-generator"
description = "Datamodel Code Generator"
readme.content-type = "text/markdown"
readme.file = "README.md"
license = "MIT"
authors = [ { name = "Koudai Aono", email = "koxudaxi@gmail.com" } ]
requires-python = ">=3.9"
classifiers = [
        "Development Status :: 4 - Beta",
        "Natural Language :: English",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: Implementation :: CPython"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
# language=RegExp
pattern = '^(?P<base>\d+\.\d+\.\d+)(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?$'

[tool.poetry-dynamic-versioning.substitution]
files = ["*/version.py"]
patterns = ["(^version: str = ')[^']*(')"]


[tool.poetry.scripts]
datamodel-codegen = "datamodel_code_generator.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
pydantic =  [
    {extras = ["email"], version = ">=1.5.1,<3.0,!=2.4.0", python = "<3.10"},
    {extras = ["email"], version = ">=1.9.0,<3.0,!=2.4.0", python = "~3.10"},
    {extras = ["email"], version = ">=1.10.0,<3.0,!=2.4.0", python = "^3.11"},
    {extras = ["email"], version = ">=1.10.0,!=2.0.0,!=2.0.1,<3.0,!=2.4.0", python = "^3.12"}
]
argcomplete = ">=1.10,<4.0"
jinja2 = ">=2.10.1,<4.0"
inflect = ">=4.1.0,<6.0"
black = ">=19.10b0"
isort = ">=4.3.21,<6.0"
genson = ">=1.2.1,<2.0"
packaging = "*"
prance = { version = ">=0.18.2", optional = true }
openapi-spec-validator = { version = ">=0.2.8,<0.7.0", optional = true }
toml = { version = ">=0.10.0,<1.0.0", python = "<3.11" }
PySnooper = { version = ">=0.4.1,<2.0.0", optional = true }
httpx = { version = "*", optional = true }
pyyaml = ">=6.0.1"
graphql-core = {version = "^3.2.3", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = ">6.1"
pytest-benchmark = "*"
pytest-cov = ">=2.12.1"
pytest-mock = "*"
mypy = ">=1.4.1,<1.5.0"
black = "^23.3.0"
freezegun = "*"
types-Jinja2 = "*"
types-PyYAML = "*"
types-toml = "*"
types-setuptools = ">=67.6.0.5,<70.0.0.0"
pydantic = "*"
httpx = ">=0.24.1"
PySnooper = "*"
ruff = ">=0.0.290,<0.5.7"
ruff-lsp = ">=0.0.39,<0.0.41"
pre-commit = "*"
pytest-xdist = "^3.3.1"
prance = "*"
openapi-spec-validator = "*"
pytest-codspeed = "^2.2.0"


[tool.poetry.extras]
http = ["httpx"]
graphql = ["graphql-core"]
debug = ["PySnooper"]
validation = ["prance", "openapi-spec-validator"]

[tool.ruff]
line-length = 120
extend-exclude = [ "tests/data" ]
format.preview = true
format.docstring-code-format = true
lint.select = [
  "ALL",
]
lint.ignore = [
  "ANN401", # Any as type annotation is allowed
  "C901",   # complex structure
  "COM812", # Conflict with formatter
  "CPY",    # No copyright statements
  "D",      # limited documentation
  "DOC",    # limited documentation
  "FIX002", # line contains to do
  "ISC001", # Conflict with formatter
  "S101",   # can use assert
  "TD002",  # missing to do author
  "TD003",  # missing to do link
  "TD004",  # missing colon in to do
]
lint.per-file-ignores."tests/**/*.py" = [
  "FBT",     # don't care about booleans as positional arguments in tests
  "INP001",  # no implicit namespace
  "PLC2701", # private import is fine
  "PLR0913", # as many arguments as want
  "PLR0915", # can have longer test methods
  "PLR0917", # as many arguments as want
  "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
  "S",       # no safety concerns
  "SLF001",  # can test private methods
]
lint.isort = { known-first-party = [
  "datamodel_code_generator",
  "tests",
], required-imports = [
  "from __future__ import annotations",
] }

lint.preview = true

[tool.codespell]
skip = '.git,*.lock,tests'

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  "ignore:^.*The `parse_obj` method is deprecated; use `model_validate` instead.*",
  "ignore:^.*The `__fields_set__` attribute is deprecated, use `model_fields_set` instead.*",
  "ignore:^.*The `dict` method is deprecated; use `model_dump` instead.*",
  "ignore:^.*The `copy` method is deprecated; use `model_copy` instead.*",
  "ignore:^.*`--validation` option is deprecated.*",
  "ignore:^.*Field name `name` is duplicated on Pet.*",
  "ignore:^.*format of 'unknown-type' not understood for 'string' - using default.*",
  "ignore:^.*unclosed file.*",
  "ignore:^.*black doesn't support `experimental-string-processing` option for wrapping string literal in .*",
  "ignore:^.*jsonschema.exceptions.RefResolutionError is deprecated as of version 4.18.0. If you wish to catch potential reference resolution errors, directly catch referencing.exceptions.Unresolvable..*",
  "ignore:^.*`experimental string processing` has been included in `preview` and deprecated. Use `preview` instead..*",
]
norecursedirs = "tests/data/*"
verbosity_assertions = 2

[tool.coverage]
html.skip_covered = false
html.show_contexts = false
paths.source = [
  "src",
  ".tox*/*/lib/python*/site-packages",
  ".tox*\\*\\Lib\\site-packages",
  "*/src",
  "*\\src",
]
paths.other = [
  ".",
  "*/datamodel-code-generator",
  "*\\datamodel-code-generator",
]
run.dynamic_context = "none"
run.omit = [ "tests/data/*" ]
report.fail_under = 88
run.parallel = true
run.plugins = [
  "covdefaults",
]
covdefaults.subtract_omit = "*/__main__.py"

[tool.pyright]
reportPrivateImportUsage = false

[tool.pydantic-pycharm-plugin]
ignore-init-method-arguments = true
parsable-types.str = [ "int", "float" ]

[tool.uv]
conflicts = [
  [
    { group = "black24" },
    { group = "black22" },
    { group = "black23" },
    { group = "dev" },
  ],
]
