[tool.poetry]
name = "datamodel-code-generator"
version = "0.0.0"
description = "Datamodel Code Generator"
authors = ["Koudai Aono <koxudaxi@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/koxudaxi/datamodel-code-generator"
repository = "https://github.com/koxudaxi/datamodel-code-generator"


classifiers = [
        "Development Status :: 4 - Beta",
        "Natural Language :: English",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: Implementation :: CPython"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
# language=RegExp
pattern = '^(?P<base>\d+\.\d+\.\d+)(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?$'

[tool.poetry-dynamic-versioning.substitution]
files = ["*/version.py"]
patterns = ["(^version: str = ')[^']*(')"]


[tool.poetry.scripts]
datamodel-codegen = "datamodel_code_generator.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
pydantic =  [
    {extras = ["email"], version = ">=1.5.1,<3.0,!=2.4.0", python = "<3.10"},
    {extras = ["email"], version = ">=1.9.0,<3.0,!=2.4.0", python = "~3.10"},
    {extras = ["email"], version = ">=1.10.0,<3.0,!=2.4.0", python = "^3.11"},
    {extras = ["email"], version = ">=1.10.0,!=2.0.0,!=2.0.1,<3.0,!=2.4.0", python = "^3.12"}
]
argcomplete = ">=1.10,<4.0"
jinja2 = ">=2.10.1,<4.0"
inflect = ">=4.1.0,<6.0"
black = ">=19.10b0"
isort = ">=4.3.21,<6.0"
genson = ">=1.2.1,<2.0"
packaging = "*"
prance = { version = ">=0.18.2", optional = true }
openapi-spec-validator = { version = ">=0.2.8,<0.7.0", optional = true }
toml = { version = ">=0.10.0,<1.0.0", python = "<3.11" }
PySnooper = { version = ">=0.4.1,<2.0.0", optional = true }
httpx = { version = "*", optional = true }
pyyaml = ">=6.0.1"
graphql-core = {version = "^3.2.3", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = ">6.1"
pytest-benchmark = "*"
pytest-cov = ">=2.12.1"
pytest-mock = "*"
mypy = ">=1.4.1,<1.5.0"
black = "^23.3.0"
freezegun = "*"
types-Jinja2 = "*"
types-PyYAML = "*"
types-toml = "*"
types-setuptools = ">=67.6.0.5,<70.0.0.0"
pydantic = "*"
httpx = ">=0.24.1"
PySnooper = "*"
ruff = ">=0.0.290,<0.5.7"
ruff-lsp = ">=0.0.39,<0.0.41"
pre-commit = "*"
pytest-xdist = "^3.3.1"
prance = "*"
openapi-spec-validator = "*"
pytest-codspeed = "^2.2.0"


[tool.poetry.extras]
http = ["httpx"]
graphql = ["graphql-core"]
debug = ["PySnooper"]
validation = ["prance", "openapi-spec-validator"]

[tool.ruff]
line-length = 88
extend-select = ['Q', 'RUF100', 'C4', 'UP', 'I']
flake8-quotes = {inline-quotes = 'single', multiline-quotes = 'double'}
target-version = 'py37'
ignore = ['E501', 'UP006', 'UP007', 'Q000', 'Q003' ]
extend-exclude = ['tests/data']

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
plugins = "pydantic.mypy"

ignore_missing_imports = true
follow_imports = "silent"
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = false
warn_untyped_fields = true

[tool.codespell]
skip = '.git,*.lock,tests'

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  "ignore:^.*The `parse_obj` method is deprecated; use `model_validate` instead.*",
  "ignore:^.*The `__fields_set__` attribute is deprecated, use `model_fields_set` instead.*",
  "ignore:^.*The `dict` method is deprecated; use `model_dump` instead.*",
  "ignore:^.*The `copy` method is deprecated; use `model_copy` instead.*",
  "ignore:^.*`--validation` option is deprecated.*",
  "ignore:^.*Field name `name` is duplicated on Pet.*",
  "ignore:^.*format of 'unknown-type' not understood for 'string' - using default.*",
  "ignore:^.*unclosed file.*",
  "ignore:^.*black doesn't support `experimental-string-processing` option for wrapping string literal in .*",
  "ignore:^.*jsonschema.exceptions.RefResolutionError is deprecated as of version 4.18.0. If you wish to catch potential reference resolution errors, directly catch referencing.exceptions.Unresolvable..*",
  "ignore:^.*`experimental string processing` has been included in `preview` and deprecated. Use `preview` instead..*",
]
norecursedirs = "tests/data/*"
verbosity_assertions = 2

[tool.coverage]
html.skip_covered = false
html.show_contexts = false
paths.source = [
  "src",
  ".tox*/*/lib/python*/site-packages",
  ".tox*\\*\\Lib\\site-packages",
  "*/src",
  "*\\src",
]
paths.other = [
  ".",
  "*/datamodel-code-generator",
  "*\\datamodel-code-generator",
]
run.dynamic_context = "none"
run.omit = [ "tests/data/*" ]
report.fail_under = 88
run.parallel = true
run.plugins = [
  "covdefaults",
]
covdefaults.subtract_omit = "*/__main__.py"

[tool.coverage.report]
ignore_errors = true
exclude_lines = [
    "if self.debug:",
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if not TYPE_CHECKING:"]

omit = ["tests/*"]

[tool.pyright]
reportPrivateImportUsage = false

[tool.pydantic-pycharm-plugin]
ignore-init-method-arguments = true
parsable-types.str = [ "int", "float" ]

[tool.pydantic-pycharm-plugin.parsable-types]
# str field may parse int and float
str = ["int", "float"]

[tool.uv]
conflicts = [
  [
    { group = "black24" },
    { group = "black22" },
    { group = "black23" },
    { group = "dev" },
  ],
]
