# generated by datamodel-codegen:
#   filename:  test_const_no_allof.json
#   timestamp: 2025-10-23T15:18:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BookTransferTransaction(BaseModel):
    family: str = Field(
        'TRANSFER', const=True, description='TRANSFER - Book Transfer Transaction'
    )
