default:
  repo: privacy-com/lithic-schemas
  branch: john-open-api-1
  output_module_path: "ledger_api_generated/generated"
  args: >
    --input-file-type jsonschema
    --collapse-root-models
    --target-python-version 3.12
    --use-title-as-name
    --reuse-model
    --use-pendulum
    --base-class ledger_api_generated.common.BaseResponse

sources:
  - input: jsonschema/customer-facing/treasury/ledger/external_resource.json
  - input: jsonschema/customer-facing/treasury/ledger/external_resource_type.json
  - input: jsonschema/customer-facing/treasury/ledger/external_payment_response.json
