# generated by datamodel-codegen:
#   filename:  test_const_allof.json
#   timestamp: 2025-10-23T15:16:31+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class BaseTransaction(BaseModel):
    id: Optional[str] = None


class ManagementOperationTransaction(BaseTransaction):
    family: str = Field(
        ...,
        const=True,
        description='MANAGEMENT_OPERATION - Management Operation Transaction',
    )
