# generated by datamodel-codegen:
#   filename:  financial_transaction.json
#   timestamp: 2025-07-21T17:17:44+00:00

from __future__ import annotations

from typing import Optional

from pydantic import Field

from .unified_base_transaction import UnifiedBaseTransaction


class FinancialTransaction(UnifiedBaseTransaction):
    specific_field: Optional[str] = Field(
        None, description='A field specific to financial transactions'
    )
